package controller;

import java.io.IOException;
import com.adyen.model.checkout.CheckoutPaymentsAction;
import com.adyen.model.checkout.PaymentsDetailsRequest;
import com.adyen.model.checkout.PaymentsRequest;
import com.adyen.model.checkout.PaymentsResponse;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

public class FrontendParser {
    private static final Gson gson = new GsonBuilder().create();

    // Deserialize payment information passed from frontend. Requires TypeAdapter for PaymentMethodDetails interface
    public static PaymentsRequest parsePayment(String body) {
        return gson.fromJson(body, PaymentsRequest.class);
    }

    // Deserialize PaymentDetails generated by component
    public static PaymentsDetailsRequest parseDetails(String body) {
        return gson.fromJson(body, PaymentsDetailsRequest.class);
    }

    // Format response being passed back to frontend. Only leave resultCode and action. Don't need to pass back
    // The rest of the information
    public static PaymentsResponse formatResponseForFrontend(PaymentsResponse unformattedResponse) throws IOException {

        PaymentsResponse.ResultCodeEnum resultCode = unformattedResponse.getResultCode();
        if (resultCode != null) {
            PaymentsResponse newPaymentsResponse = new PaymentsResponse();
            newPaymentsResponse.setResultCode(resultCode);

            CheckoutPaymentsAction action = unformattedResponse.getAction();
            if (action != null) {
                newPaymentsResponse.setAction(action);
            }
            return newPaymentsResponse;
        } else {
            throw new IOException();
        }
    }
}
